# Generated by Django 5.2.8 on 2025-11-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_ban_reason_user_banned_at_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key_rsa',
            field=models.TextField(blank=True, help_text='RSA-2048 public key for encrypted messages (Base64 SPKI format)', null=True),
        ),
    ]
