# Generated by Django 5.2.8 on 2025-11-22 15:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forum_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('forum_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forums',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('subforum_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'domains',
                'indexes': [models.Index(fields=['domain_name'], name='domains_domain__def5b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('subforum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subforum_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('post_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subforums', to='db.domain')),
                ('parent_forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subforums', to='db.forum')),
            ],
            options={
                'db_table': 'subforums',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-50 characters, alphanumeric with _ or -', regex='^[a-zA-Z0-9_-]{3,50}$')])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['google_id'], name='users_google__d35fe6_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Tag name must be alphanumeric with _ or -', regex='^[a-zA-Z0-9_-]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to='db.user')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SubforumSubscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='db.subforum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subforum_subscriptions', to='db.user')),
            ],
            options={
                'db_table': 'subforum_subscriptions',
            },
        ),
        migrations.AddField(
            model_name='subforum',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subforums', to='db.user'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='db.user')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to='db.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Title contains invalid characters', regex="^[a-zA-Z0-9 .,!?\\'À-ÿ-]+$")])),
                ('content', models.TextField(max_length=10000)),
                ('content_signature', models.CharField(blank=True, max_length=512, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subforum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='db.subforum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='db.user')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_content', models.TextField()),
                ('encryption_key_sender', models.CharField(max_length=512)),
                ('encryption_key_receiver', models.CharField(max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='db.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='db.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='db.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='db.user')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='db.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='db.user')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forums', to='db.user'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='db.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='db.user')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='db.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='db.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='db.user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='db.user')),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('report', 'Report'), ('resolve_report', 'Resolve Report')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='db.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='db.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('settings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='db.user')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('post_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='db.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='db.tag')),
            ],
            options={
                'db_table': 'post_tags',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('forum_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tags', to='db.forum')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tags', to='db.tag')),
            ],
            options={
                'db_table': 'forum_tags',
                'unique_together': {('forum', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name'], name='tags_tag_nam_91d860_idx'),
        ),
        migrations.AddIndex(
            model_name='subforumsubscription',
            index=models.Index(fields=['user'], name='subforum_su_user_id_6d6081_idx'),
        ),
        migrations.AddIndex(
            model_name='subforumsubscription',
            index=models.Index(fields=['subforum'], name='subforum_su_subforu_510afb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subforumsubscription',
            unique_together={('user', 'subforum')},
        ),
        migrations.AddIndex(
            model_name='subforum',
            index=models.Index(fields=['parent_domain'], name='subforums_parent__08dca0_idx'),
        ),
        migrations.AddIndex(
            model_name='subforum',
            index=models.Index(fields=['parent_forum'], name='subforums_parent__88e8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='subforum',
            index=models.Index(fields=['creator'], name='subforums_creator_e11556_idx'),
        ),
        migrations.AddConstraint(
            model_name='subforum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_domain__isnull', False), ('parent_forum__isnull', True)), models.Q(('parent_domain__isnull', True), ('parent_forum__isnull', False)), _connector='OR'), name='subforum_one_parent'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='reports_reporte_5cbb43_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_e83c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id'], name='reports_target__f1c53d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='posts_user_id_05c508_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['subforum'], name='posts_subforu_7e0e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['subforum', '-created_at'], name='posts_subforu_9e8210_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='messages_receive_432d39_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='messages_created_17cff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='message_not_self'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='memberships_user_id_790436_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['forum'], name='memberships_forum_i_d29d0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'forum')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='likes_user_id_4c8dad_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='likes_post_id_cf2001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['creator'], name='forums_creator_e67712_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['forum_name'], name='forums_forum_n_6f48e1_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['created_at'], name='forums_created_fde5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='follows_followe_ca9b09_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='follows_followi_dcb467_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['status'], name='follows_status_4a112d_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status'], name='follows_followe_c26443_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='follow_not_self'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='comments_parent__4366da_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='comments_created_5a6deb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comments_post_id_8fd787_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='blocks_blocker_42b25f_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='blocks_blocked_0ecc50_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_not_self'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_logs_action__168beb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'),
        ),
    ]
