# Generated by Django 5.2.8 on 2025-11-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_google__d35fe6_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='firebase_uid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE user_profiles SET privacy = (privacy = 'public');
            """,
            reverse_sql="""
            UPDATE user_profiles SET privacy = CASE WHEN privacy THEN 'public' ELSE 'private' END;
            """,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_uid'], name='users_firebas_361636_idx'),
        ),
    ]
