# Generated by Django 5.2.8 on 2025-12-01 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_message_deleted_by_receiver_and_more"),
        ("db", "0002_remove_user_users_google__d35fe6_idx_and_more"),
    ]

    operations = []
