# Generated by Django 5.2.9 on 2025-12-08 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_merge_20251202_0000"),
    ]

    operations = [
        migrations.AddField(
            model_name="subforum",
            name="forum_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subforums_in_forum",
                to="db.forum",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="forum_name",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="subforum",
            name="subforum_name",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
