# Generated by Django 5.2.8 on 2025-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_add_user_public_key_rsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_aes_key',
            field=models.TextField(blank=True, help_text="AES key encrypted with recipient's RSA public key (Base64)", null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
